/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * proto/qiita.proto
 * OpenAPI spec version: version not set
 */
export type QiitaServiceSearchArticlesParams = {
/**
 * ユーザーからの検索ワード
 */
query?: string;
};

export interface RpcStatus {
  code?: number;
  details?: ProtobufAny[];
  message?: string;
}

export interface QiitaArticle {
  author?: string;
  publishedAt?: string;
  title?: string;
  url?: string;
}

export interface QiitaSearchResponse {
  articles?: QiitaArticle[];
}

export interface ProtobufAny {
  '@type'?: string;
  [key: string]: unknown ;
}

